---

- name: Add default packages
  hosts: all
  become: true 
  tags: 
    - newborn

  tasks:
   
  - name: Install EPEL repository
    ansible.builtin.dnf:
     name: epel-release
     state: present
    when: ansible_distribution == "Rocky" 

  - name: Ensure default packcages are installed (OS Rocky)
    ansible.builtin.dnf: 
      name:
            - net-tools
            - curl
            - wget
            - vim
            - htop
            - bash-completion
            - rsync
            - tree 
      state: present
      update_cache: yes
    when: ansible_distribution == "Rocky"

  - name: Ensure default packcages are installed (OS Ubuntu)
    ansible.builtin.apt: 
      name: 
            - net-tools
            - curl
            - wget
            - vim
            - htop
            - bash-completion
            - rsync
            - tree  
      state: present
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: web-servers
  become: true
  tags: apache   
  tasks:

  - name: install httpd/apache packages with dependencies
    ansible.builtin.dnf: 
      name: httpd 
      state: latest
      update_cache: yes

  - name: Start and enable httpd service
    service:
      name: httpd
      state: started
      enabled: yes

  - name: Allow HTTP
    firewalld:
      service: http
      permanent: true
      state: enabled
      immediate: true
